[workspace]
resolver = "2"

members = ["shared", "database", "server"]

[profile.release]
opt-level = 3
codegen-units = 1
panic = 'abort'
lto = "thin"
debug = false
incremental = false
overflow-checks = false
