name: "rinha"

services:
  loadbalancer:
    build:
      context: .
      dockerfile: ./loadbalancer/Dockerfile
    depends_on:
      - server1
      - server2
    network_mode: "host"
    restart: unless-stopped
    stdin_open: false
    tty: false

  server1: &server
    build:
      context: .
      dockerfile: ./server/Dockerfile
    depends_on:
      - database
    network_mode: "host"
    restart: unless-stopped
    stdin_open: false
    tty: false

  server2:
    <<: *server
    environment:
      - TCP_PORT=8081
      - UDP_PORT=4041

  database:
    build:
      context: .
      dockerfile: ./database/Dockerfile
    network_mode: "host"
    restart: unless-stopped
    stdin_open: false
    tty: false
