name: "rinha"

services:
  # loadbalancer:
  #   build:
  #     context: loadbalancer
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - server1
  #     - server2
  #   restart: unless-stopped
  #   network_mode: host
  #   stdin_open: false
  #   tty: false

  server1: &server
    build:
      context: .
      dockerfile: ./server/Dockerfile
    depends_on:
      - database
    environment:
      - TCP_PORT=9999
      - UDP_PORT=4040
    restart: unless-stopped
    network_mode: host
    stdin_open: false
    tty: false

  # server2:
  #   <<: *server
  #   depends_on:
  #     - database
  #   environment:
  #     - TCP_PORT=8081
  #     - UDP_PORT=4041

  database:
    build:
      context: .
      dockerfile: ./database/Dockerfile
    restart: unless-stopped
    network_mode: host
    stdin_open: false
    tty: false
