name: "rinha"

services:
  proxy:
    image: haproxy
    ports:
      - "9999:9999"
    depends_on:
      - api1
      - api2
    volumes:
      - ./haproxy:/usr/local/etc/haproxy

  # loadbalancer:
  #   build:
  #     context: loadbalancer
  #     dockerfile: Dockerfile
  #   ports:
  #     - "9999:9999/tcp"
  #   depends_on:
  #     - api1
  #     - api2
  #   restart: unless-stopped
  #   stdin_open: false
  #   tty: false

  api1: &server
    build:
      context: .
      dockerfile: ./server/Dockerfile
    depends_on:
      - database
    environment:
      - TCP_PORT=80
    restart: unless-stopped
    stdin_open: false
    tty: false

  api2:
    <<: *server
    depends_on:
      - database
    environment:
      - TCP_PORT=80

  database:
    build:
      context: .
      dockerfile: ./database/Dockerfile
    restart: unless-stopped
    stdin_open: false
    tty: false
