name: "rinha"

services:
  proxy:
    image: haproxy
    ports:
      - "9999:9999"
    depends_on:
      - server1
      - server2
    volumes:
      - ./haproxy:/usr/local/etc/haproxy

  server1: &server
    build:
      context: .
      dockerfile: ./server/Dockerfile
    depends_on:
      - database
    environment:
      - TCP_PORT=80
      - DB_URL=database
    restart: unless-stopped
    stdin_open: false
    tty: false

  server2:
    <<: *server

  database:
    build:
      context: .
      dockerfile: ./database/Dockerfile
    restart: unless-stopped
    stdin_open: false
    tty: false
