FROM rust:slim-buster as build

# create a new empty shell project
COPY /db /db
COPY /api /api
COPY /shared /shared

# copy over your manifests
COPY ./Cargo.toml ./Cargo.toml

# this build step will cache your dependencies
RUN cargo build --release

# our final base
FROM debian:buster-slim

# update the package list and install runtime dependencies
RUN apt-get update && rm -rf /var/lib/apt/lists/*

# copy the build artifact from the build stage
COPY --from=build /target/release/db .

# set the startup command to run your binary
CMD ["./db"]
