[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
atoi = "2.0.0"
bincode = "1.3.3"
httparse = "1.8.0"
serde = "1.0.196"
serde_bytes = "0.11.14"
serde_json = "1.0.113"
shared = { path = "../shared" }
