[package]
edition = "2021"
name = "database"
version = "0.1.0"

[dependencies]
bincode = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
shared = { path = "../shared" }
smallvec = { workspace = true, features = ["write"] }
# flame = "0.2.2"
