[package]
edition = "2021"
name = "database"
version = "0.1.0"

[dependencies]
bincode = "1.3"
bytes = "1.5"
serde = { version = "1.0", features = ["derive"] }
shared = { path = "../shared" }
smallvec = "1.13"

# mimalloc = "0.1.39"
# flame = "0.2.2"
