[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
# atoi = "2.0.0"
bincode = "1.3.3"
httparse = "1.8.0"
# mimalloc = "0.1.39"
serde = "1.0.196"
serde_bytes = "0.11.14"
serde_json = "1.0.113"
shared = { path = "../shared" }
simd-json = "0.13.8"
# snmalloc-rs = "0.3.4"
